import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

export default [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'graphify-out/**',
      'out/**',
      'build/**',
      // Generated by `next dev`/`next build`; not ours to lint.
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // Tailwind/PostCSS configs load plugins with require() by convention.
    files: ['*.config.ts', '*.config.mjs', '*.config.js'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    rules: {
      // The codebase leans on `any` for Firestore payloads and speech-recognition
      // events, which are untyped upstream. Warn so new cases are visible without
      // failing the build on existing ones.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
    },
  },
];
